#+-----------------------------------------------------------------------------------------+
#|                                M A I N   W O R K F L O W                                |
#+-----------------------------------------------------------------------------------------+
name: main
#+-----------------------------------------------------------------------------------------+
#|                            E X T E R N A L   T R I G G E R S                            |
#+-----------------------------------------------------------------------------------------+
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# * * * * *  UTC (Convert to Singapore: +0800)
# ┬ ┬ ┬ ┬ ┬
# │ │ │ │ └───── day of week (0 - 7) (0 to 6 are Sunday to Saturday, or use names; 7 is Sunday, the same as 0)
# │ │ │ └────────── month (1 - 12)
# │ │ └─────────────── day of month (1 - 31)
# │ └──────────────────── hour (0 - 23)
# └───────────────────────── min (0 - 59)
on:
  #push:
  #pull_request:
  repository_dispatch:
    types: udemyenrol
  schedule:
    - cron:  '1 0 * * *'
jobs:
  #+-----------------------------------------------------------------------------------------+
  #|                                 C U S T O M   J O B                                     |
  #+-----------------------------------------------------------------------------------------+
  udemyenrol:
    #----------------------------------------
    # Type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      #---------------------------------------------------------
      # Runs third-party actions
      #   Checks out your repository under $GITHUB_WORKSPACE
      #   Setups Python and specify version
      - uses: actions/checkout@v2
      - name: List directories
        run: ls -laR
        working-directory: ./udemyenrol
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      #------------------------------------------------
      # Runs your custom action
      - name: udemyenrol_app
        uses: ./udemyenrol
        with:
          entrypoint: python3
          args: udemyenrol/app.py
          gmail: ${{ secrets.GMAIL }}
          gmail_app_password: ${{ secrets.GMAIL_APP_PASSWORD }}
      #----------------------
      # Update git repository
      - name: Commit and push if changed
        run: |-
          git add .
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "Updated udemyenrol.md" -a || echo "No changes to commit"
          git push          
